#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# 	Configure HAproxy so that it send traffic to web-01 and web-02
# 	Distribute requests using a roundrobin algorithm

sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0.\*

config="
frontend my_frontend
	bind *:80
	mode http
	default_backend my_backend

backend my_backend
	balance roundrobin
	server 58042-web-01 18.234.106.217:80 check
	server 58042-web-02 100.25.30.148:80 check
"

echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Backup config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
